apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  sources:
  - repoURL: oci://ghcr.io/kgateway-dev/charts
    chart: kgateway-crds
    targetRevision: "2.3.4"
    helm:
      releaseName: kgateway-crds
  - repoURL: oci://ghcr.io/kgateway-dev/charts
    chart: kgateway
    targetRevision: "2.3.4"
    helm:
      releaseName: kgateway
  destination:
    server: https://kubernetes.default.svc
    namespace: kgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
